name: example
description: Demonstrates how to use the platform api.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  platform:
    path: ../

dev_dependencies:
  lints: ^6.1.0
