name: lints
version: 6.1.0
description: >
  Official Dart lint rules. Defines the 'core' and 'recommended' set of lints
  suggested by the Dart team.
repository: https://github.com/dart-lang/core/tree/main/pkgs/lints
issue_tracker: https://github.com/dart-lang/core/issues?q=is%3Aissue+is%3Aopen+label%3Apackage%3Alints

topics:
  - analysis
  - lints

environment:
  sdk: ^3.8.0

# NOTE: Code is not allowed in this package - do not add dependencies.
# dependencies:

dev_dependencies:
  http: ^1.0.0
  path: ^1.8.0
  yaml: ^3.1.0
