name: platform
description: A pluggable, mockable platform information abstraction for Dart.
repository: https://github.com/dart-lang/core/tree/main/pkgs/platform
issue_tracker: https://github.com/dart-lang/core/issues
version: 3.2.0-wip

environment:
  # IF UPDATED: Also updateSDK version in pubspecs in `example/` and `out/`.
  sdk: ^3.10.0

dependencies:
  meta: ^1.10.0

dev_dependencies:
  dart_flutter_team_lints: ^3.5.0
  test: ^1.16.8

topics:
  - information
  - platform
