name: args
version: 2.7.0
description: >-
  Library for defining parsers for parsing raw command-line arguments into a set
  of options and values using GNU and POSIX style options.
repository: https://github.com/dart-lang/core/tree/main/pkgs/args
issue_tracker: https://github.com/dart-lang/core/issues?q=is%3Aissue+is%3Aopen+label%3Apackage%3Aargs

topics:
  - cli

environment:
  sdk: ^3.3.0

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  test: ^1.16.6
