name: convert
version: 3.1.3-wip
description: >-
  Utilities for converting between data representations.
  Provides a number of Sink, Codec, Decoder, and Encoder types.
repository: https://github.com/dart-lang/core/tree/main/pkgs/convert
issue_tracker: https://github.com/dart-lang/core/issues?q=is%3Aissue+is%3Aopen+label%3Apackage%3Aconvert

environment:
  sdk: ^3.4.0

dependencies:
  typed_data: ^1.3.0

dev_dependencies:
  benchmark_harness: ^2.2.0
  dart_flutter_team_lints: ^3.0.0
  test: ^1.17.0
